[colors]
primary.background = "#183f25"
primary.foreground = "#f1f4f2"
cursor.text = "#183f25"
cursor.cursor = "#f1f4f2"

[colors.normal]
black = "#183f25"   red = "#ff6b6b"    green = "#80b946"  yellow = "#cca24d"
blue = "#9deaea"    magenta = "#f0c3cb" cyan = "#2b879e"   white = "#f1f4f2"

[colors.bright]
black = "#1a4529"   red = "#ff7676"    green = "#8dcc4d"  yellow = "#e0b255"
blue = "#adffff"    magenta = "#ffd7df" cyan = "#2f95ae"   white = "#ffffff"
