# Шөнө (Night)
[colors]
primary.background = "#0d1615"
primary.foreground  = "#d8e1e5"
cursor.text = "#0d1615"
cursor.cursor = "#d8e1e5"

[colors.normal]
black = "#0d1615"
red = "#9d4a40"
green = "#4a7d6a"
yellow = "#b0a87a"
blue = "#6d8dad"
magenta = "#c7958d"
cyan = "#5a9b9e"
white = "#d8e1e5"

[colors.bright]
black = "#1a2328"
red = "#c76a5d"
green = "#689f8e"
yellow = "#c8c192"
blue = "#8fb3d9"
magenta = "#e0aeaa"
cyan = "#7dbfc5"
white = "#2a363c"
