[colors]
primary.background = "#F2F7F5"
primary.foreground = "#1C332D"
cursor.text = "#F2F7F5"
cursor.cursor = "#1C332D"

[colors.normal]
black = "#F2F7F5"   red = "#C4675D"    green = "#4E9A6C"  yellow = "#D5B677"
blue = "#5B9A9D"    magenta = "#B57E8C" cyan = "#3f8895"   white = "#1C332D"

[colors.bright]
black = "#dadedd"   red = "#b05d54"    green = "#468b61"  yellow = "#c0a46b"
blue = "#528b8d"    magenta = "#a3717e" cyan = "#397a86"   white = "#192e29"
