[colors]
primary.background = "#0E1A16"
primary.foreground = "#C5D6D0"
cursor.text = "#0E1A16"
cursor.cursor = "#C5D6D0"

[colors.normal]
black = "#0E1A16"   red = "#C4675D"    green = "#4E9A6C"  yellow = "#D5B677"
blue = "#A5D3D6"    magenta = "#D6A2AC" cyan = "#3f8895"   white = "#C5D6D0"

[colors.bright]
black = "#0f1d18"   red = "#d87166"    green = "#56a977"  yellow = "#eac883"
blue = "#b6e8eb"    magenta = "#ebb2bd" cyan = "#4596a4"   white = "#d9ebe5"
