[colors]
primary.background = "#172620"
primary.foreground = "#dfece7"
cursor.text = "#172620"
cursor.cursor = "#dfece7"

[colors.normal]
black = "#172620"
red = "#ff6b6b"    
green = "#80b946"  
yellow = "#cca24d"
blue = "#9deaea"    
magenta = "#f0c3cb" 
cyan = "#2b879e"   
white = "#dfece7"

[colors.bright]
black = "#192a23"   
red = "#ff7676"    
green = "#8dcc4d"  
yellow = "#e0b255"
blue = "#adffff"    
magenta = "#ffd7df" 
cyan = "#2f95ae"   
white = "#f5fffe"
