[colors]
primary.background = "#e5f5ea"
primary.foreground = "#161d18"
cursor.text = "#e5f5ea"
cursor.cursor = "#161d18"

[colors.normal]
black = "#e5f5ea"   red = "#cc2929"    green = "#4c890f"  yellow = "#df9b23"
blue = "#12adad"    magenta = "#b93d4d" cyan = "#0a728c"   white = "#161d18"

[colors.bright]
black = "#ceddd3"   red = "#b82525"    green = "#447b0e"  yellow = "#c98c20"
blue = "#109c9c"    magenta = "#a73745" cyan = "#09677e"   white = "#141a16"
