[colors]
primary.background = "#1C332D"
primary.foreground = "#D5E6E0"
cursor.text = "#1C332D"
cursor.cursor = "#D5E6E0"

[colors.normal]
black = "#1C332D"   red = "#E47E6E"    green = "#5EAA7C"  yellow = "#E5C788"
blue = "#B5E3E6"    magenta = "#E6B2BC" cyan = "#4FA8A7"   white = "#D5E6E0"

[colors.bright]
black = "#1f3832"   red = "#fb8b79"    green = "#67bb88"  yellow = "#fcdb96"
blue = "#c7fafd"    magenta = "#fdc4cf" cyan = "#57b9b8"   white = "#eafdf6"
