# Өглөө (Morning)
[colors]
primary.background = "#f0f5eb"
primary.foreground  = "#4a555c"
cursor.text = "#f0f5eb"
cursor.cursor = "#4a555c"

[colors.normal]
black = "#f0f5eb"
red = "#b56359"
green = "#7c9b8e"
yellow = "#c8c194"
blue = "#6d8dad"
magenta = "#d9a8ad"
cyan = "#5a9b9e"
white = "#4a555c"

[colors.bright]
black = "#e0e7eb"
red = "#c76a5d"
green = "#9dbfab"
yellow = "#e5e0a3"
blue = "#8fb3d9"
magenta = "#e0aeaa"
cyan = "#7dbfc5"
white = "#a3aeb5"
