[colors]
primary.background = "#0a1a0f"
primary.foreground = "#e2e9e4"
cursor.text = "#0a1a0f"
cursor.cursor = "#e2e9e4"

[colors.normal]
black = "#0a1a0f"   red = "#ff6b6b"    green = "#80b946"  yellow = "#cca24d"
blue = "#9deaea"    magenta = "#f0c3cb" cyan = "#2b879e"   white = "#e2e9e4"

[colors.bright]
black = "#0b1d11"   red = "#ff7676"    green = "#8dcc4d"  yellow = "#e0b255"
blue = "#adffff"    magenta = "#ffd7df" cyan = "#2f95ae"   white = "#f9fffb"
